name: Go

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: "go.mod"

      - name: Format
        run: |
          files="$(gofmt -l .)"
          if [ -n "$files" ]; then
            echo "Files need formatting:"
            echo "$files"
            exit 1
          fi

      - name: Vet
        run: go vet -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
